### ISSUE TITLE
Ampersand doesn't render as a "&"

### ISSUE THREAD

**Issue by BenCoding** [cyberhobo/ColumnFilterWidgets#11]
The Ampersand doesn't render as a "&" it renders as &amp; 
I'll use "&" or "&amp;" and it still renders incorrectly.

**Comment by cyberhobo** [comment]
There's an ampersand in the Platforms menu in the example that looks okay: http://datatables.net/extras/thirdparty/ColumnFilterWidgets/DataTables/extras/ColumnFilterWidgets/. Can you link an example of one that renders incorrectly?

**Comment by TrueOsiris** [comment]
you'll see that it's the same issue in your datatables search (if you're using that).
I believe this is because you're not using utf8_decode on your search vars.

**Comment by BenCoding** [comment]
Looks like I can't repeat the issue. But now working at a different company on different server no longer have an issue. I figure it TrueOsiris was right in that the utf8 - decodeing variable wasn't set properly for the page.
