### ISSUE TITLE
Match filters width and alignment to columns

### ISSUE THREAD

**Issue by aleger** [cyberhobo/ColumnFilterWidgets#17]
As a UI/UX designer it would be nice to have these filters match the width and alignment to columns. this way there is a clear visual of what column you are sorting and is also aesthetically pleasing. I am floating and styling the widths accordingly, but does not work very well with a fluid or responsive UI.

**Comment by cyberhobo** [comment]
Part of the reason I created this was to free the layout from column restrictions. Maybe one of the other filter projects would be better for an in-column UI, like https://github.com/vedmack/yadcf.

**Comment by cyberhobo** [comment]
Issue #14 is related, putting widgets in the table footer. It has some code that you could try.
