### ISSUE TITLE
It doesn't work when you specify aaData as an array of objects

### ISSUE THREAD

**Issue by iabdulin** [cyberhobo/ColumnFilterWidgets#20]
It tries to find column by index, but can't so throws error.
This change (line 161):
widget.iColumn = widget.oColumn['mData'];

fixes the error.

To make aiExclude work with mData instead of column indexes, we need to change line 116 to:
if ( oColumn.bVisible && sExcludeList.indexOf( '|' + oColumn.mData + '|' ) < 0 ) {

**Comment by cyberhobo** [comment]
Does the solution to issue #24 fix this also?
