### ISSUE TITLE
columnfilterwidgets

### ISSUE THREAD

**Issue by ckolouas** [cyberhobo/ColumnFilterWidgets#21]
Could you please provide me with instructions how to install the plugin to the datatables program? I need to know which files have to be modified and which directories to look at. Also what will be the code added to the files so the plugin will work.

Thanks,
Constantine

**Comment by cyberhobo** [comment]
There are some instructions in the readme, which also displayed [here](https://github.com/cyberhobo/ColumnFilterWidgets). No modifications are required, all you should need to do is load the javascript after the datatables javascript in your page then follow the [examples](http://www.datatables.net/extras/thirdparty/ColumnFilterWidgets/DataTables/extras/ColumnFilterWidgets/).
