### ISSUE TITLE
Discussion about using aaData: JSON Data

### ISSUE THREAD

**Issue by BenCoding** [cyberhobo/ColumnFilterWidgets#23]
When using aaData I was having problems passing JSON data to it while still using the Column Filter Widget. So I change one line of code and it worked. 
var sValue = oSettings.oApi._fnGetCellData(oSettings, iRow, iColumn);

See: http://datatables.net/forums/discussion/12519/select-filter-with-json-data/p1

**Comment by cyberhobo** [comment]
I think the solution for issue #24 will also fix this without calling a private function.
