### ISSUE TITLE
Memorize filter in session PHP

### ISSUE THREAD

**Issue by ArmandArthur** [cyberhobo/ColumnFilterWidgets#45]
Hello,

I would like memorize the filter in session PHP, and loading filters from PHP session to memorize the old state after changing page?

It's possible?

**Comment by cyberhobo** [comment]
This project is entirely javascript that runs in the browser, no PHP, so it's not practical to use the PHP session. Also there isn't a yet feature to provide initial values for the widgets, which we'd need to restore prior selections.

**Comment by ArmandArthur** [comment]
I found the solution.

$('class_select').val(value1).trigger('change');
$('class_select').val(value2).trigger('change');
